import { Room } from 'colyseus';
import { schema } from '@colyseus/schema';
const MW=1100,MH=720,TICK=1000/60,PR=16,DIFF={1:[1,1,1],2:[1.45,1.15,1.7],3:[1.9,1.3,2.4],4:[2.35,1.5,3.1]};
const DEF=['화염구','번개 폭발','치유의 빛','분신술'];
const SK={'화염구':[20,1500],'번개 폭발':[32,1900],'치유의 빛':[40,5000],'분신술':[28,3000],'충격파':[28,4500],'관통 사격':[24,3000],'마력 지뢰':[24,3800],'순간회피':[14,3800],'얼음 파동':[30,5000],'십자 포격':[28,4800],'회전 방패':[32,5800],'번개 토템':[34,7400],'폭풍 베기':[44,7600],'파쇄탄':[38,6400],'중력 붕괴':[52,9000],'그림자 돌진':[34,6200],'피의 참격':[48,9000]};
const SHOP={'충격파':[180,1],'관통 사격':[240,3],'마력 지뢰':[280,5],'순간회피':[320,7],'얼음 파동':[360,9],'십자 포격':[380,10],'회전 방패':[420,12],'번개 토템':[460,14]},BOSS={0:'중력 붕괴',1:'폭풍 베기',2:'그림자 돌진',3:'피의 참격',4:'파쇄탄'};
export const Player=schema({name:'string',x:'number',y:'number',angle:'number',hp:'number',maxHp:'number',mp:'number',maxMp:'number',level:'number',xp:'number',xpNext:'number',atk:'number',def:'number',gold:'number',kills:'number',alive:'boolean',color:'string',ownedSkills:{array:'string',default:[]},skillSlots:{array:'string',default:[]}});
export const Enemy=schema({id:'string',type:'string',x:'number',y:'number',hp:'number',maxHp:'number',r:'number',color:'string',isBoss:'boolean',bossType:'number'});
export const State=schema({phase:'string',wave:'number',timeLeft:'number',mapW:'number',mapH:'number',wavePartySize:'number',enemyHpMult:'number',enemyCountMult:'number',bossHpMult:'number',teamKills:'number',players:{map:Player,default:new Map()},enemies:{map:Enemy,default:new Map()}});
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),norm=(x,y)=>{const d=Math.hypot(x,y)||1;return{x:x/d,y:y/d}};
export class CoopRoom extends Room{
 state=new State();maxClients=4;input=new Map();atkCd=new Map();skillCd=new Map();buff=new Map();seq=1;timer=0;initialParty=0;runAt=0;runId='';rankEligible=true;rankReason='';
 onCreate(o){this.maxClients=clamp(Number(o?.partySize||4),2,4);Object.assign(this.state,{phase:'waiting',wave:1,mapW:MW,mapH:MH,teamKills:0});this.diff(1);this.setPatchRate(50);this.setSimulationInterval(d=>this.tick(d),TICK);this.onMessage('input',(c,p)=>this.input.set(c.sessionId,{up:!!p?.up,down:!!p?.down,left:!!p?.left,right:!!p?.right,angle:Number.isFinite(p?.angle)?p.angle:0,attacking:!!p?.attacking}));this.onMessage('ready',()=>{if(this.state.phase==='waiting')this.startRun()});this.onMessage('skill',(c,p)=>this.slot(c.sessionId,String(p?.slot||'')));this.onMessage('buySkill',(c,p)=>this.buy(c.sessionId,String(p?.skill||'')));this.onMessage('equipSkill',(c,p)=>this.equip(c.sessionId,String(p?.skill||''),Number(p?.slot)))}
 onJoin(c,o){const i=this.state.players.size,p=new Player();Object.assign(p,{name:String(o?.name||`P${i+1}`).replace(/[<>]/g,'').slice(0,12)||`P${i+1}`,x:390+i*110,y:360,angle:0,hp:120,maxHp:120,mp:80,maxMp:80,level:1,xp:0,xpNext:100,atk:10,def:0,gold:0,kills:0,alive:true,color:['#4af0ff','#ffcc33','#ff70c8','#70ff80'][i%4]});DEF.forEach(s=>{p.ownedSkills.push(s);p.skillSlots.push(s)});this.state.players.set(c.sessionId,p);this.input.set(c.sessionId,{});this.atkCd.set(c.sessionId,0);this.skillCd.set(c.sessionId,{});c.send('notice',{message:'Lv.1 / 기본 능력치 / 기본 4스킬 / 빈 장비·인벤토리 시작'});if(this.state.phase!=='waiting'){this.rankEligible=false;this.rankReason='진행 중 입장 발생'}}
 onLeave(c){if(this.state.phase!=='waiting'){this.rankEligible=false;this.rankReason='플레이 중 퇴장 발생'}this.state.players.delete(c.sessionId);this.input.delete(c.sessionId);this.atkCd.delete(c.sessionId);this.skillCd.delete(c.sessionId);if(!this.state.players.size)this.disconnect()}
 diff(n){const d=DIFF[clamp(n,1,4)];this.state.wavePartySize=n;this.state.enemyHpMult=d[0];this.state.enemyCountMult=d[1];this.state.bossHpMult=d[2]}
 startRun(){if(!this.state.players.size)return;this.initialParty=this.state.players.size;this.runAt=Date.now();this.runId=`${this.roomId}_${this.runAt}`;this.rankEligible=this.initialParty>=2;this.rankReason=this.rankEligible?'':'2인 이상만 랭킹 가능';this.wave()}
 wave(){const n=clamp(this.state.players.size,1,4);this.diff(n);this.state.phase='playing';this.timer=40000;this.state.timeLeft=40;this.state.enemies.clear();if(this.state.wave%5===0)this.spawnBoss();else{const amount=Math.round((7+this.state.wave*2)*this.state.enemyCountMult);for(let i=0;i<amount;i++)this.spawn();this.broadcast('wave',{wave:this.state.wave,amount,partySize:n,enemyHpMult:this.state.enemyHpMult,enemyCountMult:this.state.enemyCountMult,bossHpMult:this.state.bossHpMult})}}
 place(e){const s=Math.floor(Math.random()*4);e.x=s===0?20:s===1?MW-20:Math.random()*MW;e.y=s===2?20:s===3?MH-20:Math.random()*MH}
 spawn(){const e=new Enemy();e.id='e'+this.seq++;e.isBoss=false;e.bossType=-1;e.type=Math.random()<Math.min(.55,.2+this.state.wave*.015)?'fast':'normal';e.r=e.type==='fast'?12:15;e.maxHp=Math.round((e.type==='fast'?45+this.state.wave*8:70+this.state.wave*13)*this.state.enemyHpMult);e.hp=e.maxHp;e.color=e.type==='fast'?'#ff8c00':'#e03030';this.place(e);this.state.enemies.set(e.id,e)}
 spawnBoss(){const e=new Enemy();e.id='b'+this.seq++;e.isBoss=true;e.bossType=Math.floor((this.state.wave/5-1)%5);e.type='boss';e.r=32;e.maxHp=Math.round((750+this.state.wave*120)*this.state.bossHpMult);e.hp=e.maxHp;e.color=['#c030ff','#ff80ff','#20c0a0','#cc2020','#80a8ff'][e.bossType];this.place(e);this.state.enemies.set(e.id,e);this.broadcast('wave',{wave:this.state.wave,amount:1,partySize:this.state.wavePartySize,enemyHpMult:this.state.enemyHpMult,enemyCountMult:this.state.enemyCountMult,bossHpMult:this.state.bossHpMult})}
 tick(ms){const dt=ms/1000;this.state.players.forEach((p,id)=>{if(!p.alive)return;const i=this.input.get(id)||{},dx=(i.right?1:0)-(i.left?1:0),dy=(i.down?1:0)-(i.up?1:0),n=norm(dx,dy),spd=(this.buff.get(id)||0)>Date.now()?335:250;if(dx||dy){p.x=clamp(p.x+n.x*spd*dt,PR,MW-PR);p.y=clamp(p.y+n.y*spd*dt,PR,MH-PR)}p.angle=i.angle||p.angle;p.mp=clamp(p.mp+3*dt,0,p.maxMp);let a=Math.max(0,(this.atkCd.get(id)||0)-ms);this.atkCd.set(id,a);if(i.attacking&&a<=0){this.basic(id);this.atkCd.set(id,310)}const c=this.skillCd.get(id)||{};for(const k in c)c[k]=Math.max(0,c[k]-ms)});this.move(dt);if(this.state.phase==='playing'){this.timer-=ms;this.state.timeLeft=Math.max(0,this.timer/1000);if(this.dead())return this.gameOver();if(!this.state.enemies.size||this.timer<=0){this.state.phase='between';this.timer=6000;this.state.timeLeft=6;this.state.players.forEach(p=>{if(p.alive){p.hp=Math.min(p.maxHp,p.hp+p.maxHp*.15);p.mp=Math.min(p.maxMp,p.mp+25)}})}}else if(this.state.phase==='between'){this.timer-=ms;this.state.timeLeft=Math.max(0,this.timer/1000);if(this.timer<=0){this.state.wave++;this.wave()}}}
 dead(){let a=false;this.state.players.forEach(p=>{if(p.alive)a=true});return !a}
 move(dt){const gone=[];this.state.enemies.forEach((e,id)=>{if(e.hp<=0){gone.push(id);return}let t,b=Infinity;this.state.players.forEach(p=>{if(!p.alive)return;const d=(e.x-p.x)**2+(e.y-p.y)**2;if(d<b){b=d;t=p}});if(!t)return;const n=norm(t.x-e.x,t.y-e.y),s=e.isBoss?55:e.type==='fast'?112:72;e.x+=n.x*s*dt;e.y+=n.y*s*dt;if(Math.sqrt(b)<e.r+PR+4){t.hp=Math.max(0,t.hp-(e.isBoss?34:e.type==='fast'?15:22)*dt);if(t.hp<=0)t.alive=false}});gone.forEach(id=>this.kill(id))}
 kill(id){const e=this.state.enemies.get(id);if(!e)return;this.state.enemies.delete(id);this.state.teamKills++;this.state.players.forEach(p=>{p.kills++;p.gold+=e.isBoss?160:6;this.xp(p,e.isBoss?120:18)});if(e.isBoss){const s=BOSS[e.bossType];this.state.players.forEach(p=>{if(!p.ownedSkills.includes(s))p.ownedSkills.push(s);else p.gold+=120});this.broadcast('notice',{message:`보스 처치 · 전원 ${s} 해금 (보유자는 +120G)`})}}
 xp(p,v){p.xp+=v;while(p.xp>=p.xpNext){p.xp-=p.xpNext;p.xpNext=Math.floor(p.xpNext*1.2);p.level++;p.maxHp+=10;p.maxMp+=5;p.atk+=2;p.hp=Math.min(p.maxHp,p.hp+10);p.mp=Math.min(p.maxMp,p.mp+5)}}
 basic(id){const p=this.state.players.get(id),e=this.cone(p,235,.55);if(e){e.hp-=p.atk*1.25+22;this.broadcast('fx',{type:'hit',x:e.x,y:e.y,color:'#fff'})}}
 cone(p,r,a){let q,d=r;this.state.enemies.forEach(e=>{const x=e.x-p.x,y=e.y-p.y,z=Math.hypot(x,y),v=Math.abs(Math.atan2(Math.sin(Math.atan2(y,x)-p.angle),Math.cos(Math.atan2(y,x)-p.angle)));if(z<d&&v<a){q=e;d=z}});return q}
 slot(id,k){const i={q:0,w:1,e:2,r:3}[k],p=this.state.players.get(id);if(i!==undefined&&p)this.use(id,p.skillSlots[i])}
 use(id,n){const p=this.state.players.get(id),s=SK[n],cd=this.skillCd.get(id)||{};if(!p?.alive||!s||!p.ownedSkills.includes(n)||(cd[n]||0)>0||p.mp<s[0])return;p.mp-=s[0];cd[n]=s[1];this.skillCd.set(id,cd);const circle=(r,d,c)=>{this.state.enemies.forEach(e=>{if(Math.hypot(e.x-p.x,e.y-p.y)<r)e.hp-=d});this.broadcast('fx',{type:'circle',x:p.x,y:p.y,radius:r,color:c})},line=(d,w,l,c)=>{this.state.enemies.forEach(e=>{const x=e.x-p.x,y=e.y-p.y,f=Math.cos(p.angle)*x+Math.sin(p.angle)*y,z=Math.abs(-Math.sin(p.angle)*x+Math.cos(p.angle)*y);if(f>0&&f<l&&z<w)e.hp-=d});this.broadcast('fx',{type:'line',x:p.x,y:p.y,angle:p.angle,length:l,color:c})};
 if(n==='화염구')line(p.atk*2,28,460,'#ff8c00');else if(n==='관통 사격')line(p.atk*4,36,460,'#4af0f0');else if(n==='파쇄탄')line(p.atk*6,42,460,'#80a8ff');else if(n==='번개 폭발')circle(260,p.atk*2.2,'#ffc828');else if(n==='치유의 빛'){p.hp=Math.min(p.maxHp,p.hp+p.maxHp*.2);circle(70,0,'#3dc850')}else if(n==='분신술'){this.buff.set(id,Date.now()+5500);circle(80,0,'#b060ff')}else if(n==='충격파')circle(175,p.atk*4,'#4af0b0');else if(n==='마력 지뢰'){circle(35,0,'#50c0ff');setTimeout(()=>{if(this.state?.players.has(id))circle(120,p.atk*6,'#50c0ff')},900)}else if(n==='순간회피'){p.x=clamp(p.x+Math.cos(p.angle)*170,PR,MW-PR);p.y=clamp(p.y+Math.sin(p.angle)*170,PR,MH-PR);circle(30,0,'#fff')}else if(n==='얼음 파동')circle(225,p.atk*3,'#8fd8ff');else if(n==='십자 포격'){const a=p.angle;for(const ang of [0,Math.PI/2,Math.PI,Math.PI*1.5]){p.angle=ang;line(p.atk*3,32,430,'#ffcc66')}p.angle=a}else if(n==='회전 방패')circle(185,p.atk*3.3,'#a0c0ff');else if(n==='번개 토템'){for(let k=1;k<=5;k++)setTimeout(()=>{const e=this.cone(p,260,Math.PI);if(e)e.hp-=p.atk*2.2;circle(105,0,'#ffe000')},k*600)}else if(n==='폭풍 베기')circle(205,p.atk*7,'#ff80ff');else if(n==='중력 붕괴')circle(285,p.atk*8,'#c030ff');else if(n==='그림자 돌진'){line(p.atk*6,55,330,'#20c0a0');p.x=clamp(p.x+Math.cos(p.angle)*240,PR,MW-PR);p.y=clamp(p.y+Math.sin(p.angle)*240,PR,MH-PR)}else if(n==='피의 참격'){line(p.atk*7,110,300,'#cc2020');p.hp=Math.min(p.maxHp,p.hp+p.maxHp*.12)}}
 buy(id,n){const p=this.state.players.get(id),v=SHOP[n];if(!p||!v||p.ownedSkills.includes(n)||this.state.wave<v[1]||p.gold<v[0]||!['waiting','between'].includes(this.state.phase))return;p.gold-=v[0];p.ownedSkills.push(n);this.broadcast('notice',{message:`${p.name}이(가) ${n} 스킬북 구매`})}
 equip(id,n,i){const p=this.state.players.get(id);if(!p||!p.ownedSkills.includes(n)||i<0||i>3||!['waiting','between'].includes(this.state.phase))return;const old=p.skillSlots.indexOf(n);if(old>=0){const t=p.skillSlots[i];p.skillSlots[i]=n;p.skillSlots[old]=t}else p.skillSlots[i]=n}
 gameOver(){if(this.state.phase==='gameover')return;this.state.phase='gameover';const players=[];this.state.players.forEach(p=>players.push(p.name));const ok=this.rankEligible&&this.initialParty>=2&&players.length===this.initialParty;this.broadcast('gameover',{roomId:this.roomId,runId:this.runId,partySize:this.initialParty,wave:this.state.wave,kills:this.state.teamKills,survivalSec:Math.floor((Date.now()-this.runAt)/1000),players,rankEligible:ok,rankReason:ok?'':(this.rankReason||'시작 인원과 종료 인원이 다름')})}
}
